"""Add shap_values to Project

Revision ID: c49406e2eccc
Revises: 40405fa410b7
Create Date: 2026-05-30 15:55:54.994917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49406e2eccc'
down_revision: Union[str, Sequence[str], None] = '40405fa410b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('shap_values', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'shap_values')
    # ### end Alembic commands ###
